# Generated by Django 3.0.5 on 2020-06-16 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_title', models.CharField(max_length=256, verbose_name='Ad title')),
                ('offer_price', models.PositiveIntegerField(default=1, verbose_name='Ad price')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('description', models.TextField(verbose_name='Ad description')),
                ('image', models.ImageField(upload_to='ads_images', verbose_name='Ad image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Category description')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('validity', models.PositiveIntegerField(default=1)),
                ('imagescount', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(default='category_images/default.png', upload_to='category_images', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wheels_Brand', models.CharField(max_length=50)),
                ('Width', models.PositiveIntegerField(default=1)),
                ('Ratio', models.PositiveIntegerField(default=1)),
                ('Diameter', models.PositiveIntegerField(default=1)),
                ('Seasonality', models.CharField(max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tire_Condition', models.CharField(max_length=50)),
                ('On_Rims', models.CharField(max_length=50)),
                ('Year', models.PositiveIntegerField(default=1)),
                ('Make', models.CharField(max_length=250)),
                ('Model', models.CharField(max_length=250)),
                ('Width', models.PositiveIntegerField(default=1)),
                ('Aspect_Ratio', models.PositiveIntegerField(default=1)),
                ('Diameter', models.PositiveIntegerField(default=1)),
                ('Tyres_Available', models.PositiveIntegerField(default=1)),
                ('Tenure_offered', models.PositiveIntegerField(default=1)),
                ('Ad_Type', models.CharField(max_length=250)),
                ('Seasonality', models.CharField(max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad_images', verbose_name='Ad image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='core.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
