# Generated by Django 3.0.5 on 2020-06-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheels',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ad'),
        ),
    ]
