# Generated by Django 3.0.5 on 2020-06-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200616_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheels',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imagescount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='validity',
        ),
        migrations.AddField(
            model_name='ad',
            name='Ad_Type',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Aspect_Ratio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='Make',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Model',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='On_Rims',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Seasonality',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Tenure_offered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='Tire_Condition',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Tyres_Available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='Wheels_Brand',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='Width',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='Year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='core.Ad'),
        ),
        migrations.DeleteModel(
            name='Tires',
        ),
        migrations.DeleteModel(
            name='Wheels',
        ),
    ]
