# Generated by Django 3.0.5 on 2020-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200616_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Tyres_Available',
            new_name='tires_available',
        ),
        migrations.AlterField(
            model_name='ad',
            name='Year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
