# Generated by Django 2.2.5 on 2020-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200620_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=256)),
                ('Subject', models.CharField(max_length=256)),
                ('Message', models.TextField(max_length=256)),
            ],
        ),
    ]
