# Generated by Django 2.2.5 on 2020-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='tires_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
