# Generated by Django 2.2.5 on 2020-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='service_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='specials',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='wheel_color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='wheel_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
