# Generated by Django 3.0.5 on 2020-06-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200516_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('has_attributes', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedAdAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select')], default='dropdown', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tyres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_Title', models.CharField(max_length=100)),
                ('Tire_Condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('On_Rims', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Year', models.IntegerField()),
                ('Make', models.CharField(max_length=250)),
                ('Model', models.CharField(max_length=250)),
                ('Width', models.IntegerField()),
                ('Ratio', models.IntegerField()),
                ('Diameter', models.IntegerField()),
                ('Tyres_Available', models.IntegerField()),
                ('Rent_Type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=250)),
                ('Seasonality', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('All-Seasons', 'All-Seasons')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_Title', models.CharField(max_length=100)),
                ('Wheels_Brand', models.CharField(choices=[('Bridgestone', 'Bridgestone'), ('Appollo', 'Appollo'), ('Firestun', 'Firestun'), ('Racewheel', 'Racewheel')], max_length=50)),
                ('Width', models.IntegerField(default=0)),
                ('Ratio', models.IntegerField(default=0)),
                ('Diameter', models.IntegerField(default=0)),
                ('Offer_Price', models.CharField(max_length=50)),
                ('Seasonality', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('All-Seasons', 'All-Seasons')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='make',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='model',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='rent_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='year',
        ),
        migrations.AddField(
            model_name='ad',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0, verbose_name='Category description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='imagescount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='validity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.Attribute')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttributeAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='attribute name')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributead', to='core.AdType')),
                ('assigned_products', models.ManyToManyField(blank=True, related_name='attributesrelated', through='core.AssignedAdAttribute', to='core.Ad')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeAd', to='core.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='ad_types',
            field=models.ManyToManyField(blank=True, related_name='ad_attributes', through='core.AttributeAd', to='core.AdType'),
        ),
        migrations.AddField(
            model_name='assignedadattribute',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Ad'),
        ),
        migrations.AddField(
            model_name='assignedadattribute',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adassignments', to='core.AttributeAd'),
        ),
        migrations.AddField(
            model_name='assignedadattribute',
            name='values',
            field=models.ManyToManyField(to='core.AttributeValue'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedadattribute',
            unique_together={('ad', 'assignment')},
        ),
    ]
