# Generated by Django 3.0.5 on 2020-06-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200602_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tyre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tyres'),
            preserve_default=False,
        ),
    ]
