# Generated by Django 3.0.5 on 2020-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200517_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user_images', verbose_name='User image'),
            preserve_default=False,
        ),
    ]
