# Generated by Django 3.0.5 on 2020-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200602_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AccountType',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
