# Generated by Django 3.0.5 on 2020-06-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accounttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AccountType',
            new_name='Account_Type',
        ),
    ]
