# Generated by Django 3.0.5 on 2020-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200615_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Account_Type',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
