# Generated by Django 3.0.5 on 2020-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200615_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Account_type',
            field=models.CharField(choices=[('Business Account', 'Business Account'), ('Personal Account', 'Personal Account')], max_length=50),
        ),
    ]
