# Generated by Django 2.2.5 on 2020-07-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200707_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_shipping_address',
        ),
    ]
