# Generated by Django 2.2.5 on 2020-06-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ('plan_name',), 'permissions': (('subscriptions', 'Can interact with subscription details'),)},
        ),
    ]
