# Generated by Django 2.2.5 on 2020-06-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200630_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='Account_type',
            field=models.CharField(choices=[('Business Account', 'Business Account'), ('Personal Account', 'Personal Account')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='the cost per recurrence of the plan', max_digits=19, null=True),
        ),
    ]
