# Generated by Django 2.2.5 on 2020-06-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20200630_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='group',
        ),
    ]
