# Generated by Django 2.2.5 on 2020-06-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('subscriptions', '0006_remove_subscriptionplan_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='account_type',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='the Django auth group for this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='auth.Group'),
        ),
    ]
