# Generated by Django 2.2.5 on 2020-07-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionplan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlistdetail',
            name='plan_cost',
            field=models.ForeignKey(help_text='the plan costs that were billed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_cost', to='subscriptions.PlanCost'),
        ),
    ]
